### ISSUE TITLE
ReferenceError: $J is not defined

### ISSUE THREAD

**Issue by RollingSnack** [zhouhaoyu/snippets#1]
Script error in [Greasemonkey script null/跳过steam探索队列中不予显示的游戏；版本 0.1]:
ReferenceError: $J is not defined

#### Environment

- Firefox 77.0.1 (64-bit)
- Greasemonkey 4.9

#### Description

I could directly run those "$J" in the console correctly, but it failed to create the button automatically with this script.

**Comment by lpaladin** [comment]
Hi @RollingSnack , thank you for reporting that!
Now I've fixed that bug, and you may get the latest version in this repo or https://greasyfork.org/en/scripts/385636-%E4%BB%8Esteam%E6%8E%A2%E7%B4%A2%E9%98%9F%E5%88%97%E7%A7%BB%E9%99%A4%E8%A2%AB%E7%A6%81%E6%B8%B8%E6%88%8F
