### ISSUE TITLE
更新后报错了

### ISSUE THREAD

**Issue by cratexnet** [zhouhaoyu/snippets#2]
userscript.html?name=%E4%BB%8ESteam%E6%8E%A2%E7%B4%A2%E9%98%9F%E5%88%97%E7%A7%BB%E9%99%A4%E8%A2%AB%E7%A6%81%E6%B8%B8%E6%88%8F.user.js&id=285049ee-9ad2-4084-a5a5-3903e972eb84:1
ERROR: Execution of script '从Steam探索队列移除被禁游戏' failed! unsafeWindow is not defined

环境
Win10 x64 2004
Chrome 84.0.4147.105 x64
Tampermonkey 4.10

**Comment by Koan317** [comment]
Safari 14.0脚本无效
所有软件或程序都是最新版

**Comment by lpaladin** [comment]
感谢指出。已经按照 https://greasyfork.org/en/scripts/385636-%E4%BB%8Esteam%E6%8E%A2%E7%B4%A2%E9%98%9F%E5%88%97%E7%A7%BB%E9%99%A4%E8%A2%AB%E7%A6%81%E6%B8%B8%E6%88%8F/discussions/60295#comment-154928 的方案修复。
